<Project>
  <PropertyGroup>
    <OutputPath>../../bin/$(Configuration)/</OutputPath>
    <Description>.NET for the Commodore 64: a hobby project for creating 6502 C64 apps in C#</Description>
    <Authors>Jonathan Peppers; Klaus Loeffelmann</Authors>
    <PackageProjectUrl>https://github.com/jonathanpeppers/dotnes</PackageProjectUrl>
    <PackageTags>.NET C# 6502</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)../README.md" Pack="true" PackagePath="" />
  </ItemGroup>
  <Target Name="_ClearNuGetCache" BeforeTargets="Build">
    <RemoveDir Directories="$(MSBuildThisFileDirectory)../../samples/packages/$(PackageId)" />
  </Target>
</Project>
